### ISSUE TITLE
不支持.net core 3 

### ISSUE THREAD

**Issue by yuessir** [znyet/DapperExtensions#1]
DapperExtensions不支持.net core 3 
可否支援到新一點的平台呢?
感謝~

**Comment by znyet** [comment]
I have build,please download from
Lib/Dist/netcoreapp3.0.7z
Lib/Dist/netcoreapp3.1.7z

**Comment by yuessir** [comment]
Thank you 😊

**Comment by znyet** [comment]
good luck




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Catvan"<notifications@github.com&gt;; 
发送时间: 2020年4月17日(星期五) 晚上6:57
收件人: "znyet/DapperExtensions"<DapperExtensions@noreply.github.com&gt;; 
抄送: "821023977"<821023977@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [znyet/DapperExtensions] 不支持.net core 3  (#1)





 
Thank you
