### ISSUE TITLE
Codegen 的dynamic OtherData做用？

### ISSUE THREAD

**Issue by yuessir** [znyet/DapperExtensions#2]
我研究了一下您優美的代碼發現
public dynamic OtherData = new ExpandoObjec默認這行是comment的

請問什麼樣的場景需要？，在您的readme上沒看到相關說明

感謝解答

**Comment by znyet** [comment]
It's just a demo
The point is [igore]
When you need to tag non database fields
use [Igore]

**Comment by yuessir** [comment]
感謝 我看到ignoreattribute了 💯
